### ISSUE TITLE
Access to Web UI

### ISSUE THREAD

**Issue by Ergoforce1** [jantman/python-amcrest-noauth-proxy#1]
Dear Jantman,

Would there be a chance to expand your solution to access the Web UI. I already searched several days for some PHP snippets to adress the digest Auth problem as I have an home automation solution where my different cams are shown. 
Therefore I need to get rid auf the user athentication and just embed the WEB UI as an iframe within my solution.
Cheers

**Comment by jantman** [comment]
If you want the whole web UI, not just the video, it might be possible. However the web UI does _not_ use Digest authentication. On the firmware I have at least (r17 and r18) there's a login box in the actual HTML. This is submitted via HTTP POST and a session is maintained using cookies, not Digest Auth. Digest appears to only be for the CGI.

I'm not sure what home automation system you're using, but I think embedding the whole web UI as an iframe is a bit rough of a solution. You can stream low-res MJPEG with just an ``img`` tag, and if you want the full high-res stream, there are a few javascript RSTP clients out there...

**Comment by Ergoforce1** [comment]
Thank you very much for your broad answer and now I better understand why I did'nt found the "realm" regarding digest auth, when analysing the web traffic in the F12-mode of the browser. Unfortunately I have just experince with programming in C++ and know a little bit how to use PHP. My home automation just need the full Web UI, because I use the Web UI from the NVR 4108 which then shows all the cams in a nice window and is very detailed as its based on H.264 with high solution.
If there would be a chance that you add just the Web UI support for your solution it would be a great help for me and regarding my research within the amcrest forum I would think that this would be also very interesting for a lot of other people.

**Comment by jantman** [comment]
@Ergoforce1 In my tests it appears that this will not work for the web UI (at least on my cameras) because the web UI does *not* use Digest authentication, it uses a POST-based login and cookies, which this solution can't handle.

If any of the other folks on the Amcrest forum would like to experiment with this, I'd gladly accept a pull request that adds support for the web UI.

**Comment by Ergoforce1** [comment]
Thanks for your support. Cheers
